### ISSUE TITLE
sur_hypothese not working anymore?

### ISSUE THREAD

**Issue by simon-lowe** [kylebutts/vcovSUR#3]
Hi Kyle,

Thanks for the great package. When I run your example, I get: "Error: `FUN` is deprecated. Please supply your function to the `hypothesis` argument instead."
My packages should all be up-to-date, so I was wondering whether there was an update in marginaleffects? Admittedly, the error is somewhat confusing since the `hypothesis` argument is being used.

Thanks,
Simon

**Comment by kylebutts** [comment]
Hi @simon-lowe, thanks for flagging. Should be fixed now
